name: Generate and commit diagrams
on:
  pull_request:
    branches: [main]

jobs:
  update-infrastruture-diagrams:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: generate and commit diagrams
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
